// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package server

import (
	"github.com/lits01/xiaozhan/domain/engin"
	"github.com/lits01/xiaozhan/pkg/db/mysql"
	"github.com/lits01/xiaozhan/pkg/logging"
)

// Injectors from wire.go:

func InitServer() (*Server, error) {
	logger := logging.NewLogger()
	configuration := NewConfig()
	db, err := mysql.NewSqlDb(configuration)
	if err != nil {
		return nil, err
	}
	enginEngin := engin.NewEngin(configuration, logger, db)
	server := NewServer(logger, configuration, enginEngin)
	return server, nil
}
